project:
  type: "website"
  title: "Splicing Fidelity"
  output-dir: docs
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!code/"
    - "!data/"
    - "!output"
website:
  title: "Splicing Fidelity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - href: https://cdai.notion.site/Notes-0e18d7ec33cb44fc975cb9e139aa784b
        text: Notion
      - about.qmd
    background: "dark"
    search: true
  # open-graph: true
  # twitter-card:
  #   title: twitter
  #   site: "@chaodai"
  # comments:
  #   hypothesis:
  #     theme: classic
  #     openSidebar: false
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
