project:
  type: "website"
  title: "Leafcutter 2"
  output-dir: docs
  render:
    - "!archieved_analyses"
    - "!code/"
    - "!data/"
    - "!output/"
    - "!docs/"
    - "!assets/"
    - "!shiny-apps/"
    - "!analysis/"
    - "!qmd/"
    - "index.qmd"
    - "about.qmd"
    # - "slides/index.qmd"
    # - "analysis/*.pub.qmd"
    # - "qmd/*.pub.qmd"
    #- "*.qmd"
    #- "analysis/*.pub.ipynb"
website:
  title: "Splicing Fidelity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - about.qmd
    background: "dark"
    search: true
  # open-graph: true
  # twitter-card:
  #   title: twitter
  #   site: "@chaodai"
  # comments:
  #   hypothesis:
  #     theme: classic
  #     openSidebar: false
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
