# Snakemake workflow configurations

Dataset:
  Geuvadis:
    Metadata: resources/geuvadis-sample-run-pop-lookup.tsv # geuvadis meta data (all samples)
    Linked_SampleIDs: resources/geuvadis-1kgp-common-sample-id.txt # geuvadis sample IDs that have genotype in 1KGP
    Linked_1to1_SampleIDs: resources/geuvadis-1kgp-common-1to1only-sample-id.txt # linkable sample IDs that only have 1 ERR ID
  GTEx:
    Metadata: resources/GTEx-SampleID-Tissue-Lookup.csv
    Junc_meta: resources/GTEx/juncs/sampid-smts-smtsd-subjid.tsv # all sample IDs from junction file, augmented with tissue info and individual ids
    


junction_list: 
  test: resources/leafcutter_junc_files_list.txt
  Geuvadis: resources/Geuvadis_juncs.txt

intron_class:
  - resources/gencode_v43_plus_v37_productive.intron_by_transcript_BEDlike.txt.gz
  # - resources/basic_annotated_introns.txt.gz
  # - resources/IntronAnnotationsFromYang_ProductiveOnly.tsv.gz
  # - resources/intron_class_lplus1_rminus1.txt.gz

annotation:
  gencode: /project2/yangili1/cdai/genome_index/hs38/gencode.v38.primary_assembly.annotation.dataframe.csv
  gencode_v26_genes: /project2/yangili1/cdai/genome_index/hs38/gencode.v26.primary_assembly.annotation.genes.bed.gz
  gencode_v38_genes: /project2/yangili1/cdai/genome_index/hs38/gencode_gene_v38_anno.bed
  gtf:
    v43: /project2/yangili1/cdai/annotations/hg38/gencode.v43.primary_assembly.annotation.gtf.gz
  # basic_introns: /project2/yangili1/cdai/SpliFi/code/resources/IntronAnnotationsFromYang.tsv.gz # from Ben

genome38: /project2/yangili1/cdai/genome_index/hs38/GRCh38.primary_assembly.genome.fa

VCF:
  GTEx:
    HG38_v7: /project2/yangili1/cdai/genome_index/hs38/GTEx_v7/GTEx_Analysis_2017-06-05_v8_WGS_VCF_files_GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.vcf.gz
    HG38_v7_indivs: /project2/yangili1/cdai/genome_index/hs38/GTEx_v7/GTEx_Analysis_2017-06-05_v8_WGS_VCF_Indiv_ids.txt
  Geuvadis:
    HG38_1kg_b38: /project2/yangili1/cdai/SNP/1kg_b38 # this is a folder
    HG38_1kg_b38_indivs: /project2/yangili1/cdai/SNP/1kg_b38/CCDG_14151_B01_GRM_WGS_2020-08-05_individual-ids.txt

alignments:
  LCL: 
    bam: /project2/yangili1/ankeetashah/hg38_LCL #/project2/yangili1/ankeetashah/hg38_LCL/NA20807.bam
    bigwig: /project2/yangili1/ankeetashah/hg38_LCL # /project2/yangili1/ankeetashah/hg38_LCL/NA20807.bam.bw

HG38_CHROM_SIZES: /project2/yangili1/cdai/annotations/hg38/hg38.chrom.sizes