# Snakemake workflow configurations

Dataset:
  Geuvadis:
    Metadata: resources/geuvadis-sample-run-pop-lookup.tsv # geuvadis meta data (all samples)
    Linked_SampleIDs: resources/geuvadis-1kgp-common-sample-id.txt # geuvadis sample IDs that have genotype in 1KGP
    Linked_1to1_SampleIDs: resources/geuvadis-1kgp-common-1to1only-sample-id.txt # linkable sample IDs that only have 1 ERR ID
  GTEx:
    Metadata: resources/GTEx-SampleID-Tissue-Lookup.tsv


junction_list: 
  test: resources/leafcutter_junc_files_list.txt
  Geuvadis: resources/Geuvadis_juncs.txt

intron_class : resources/intron_class.txt.gz # annotated intron class: e.g. functional or noisy

annotation:
  gencode: /project2/yangili1/cdai/genome_index/hs38/gencode.v38.primary_assembly.annotation.dataframe.csv
  gencode_v26_genes: /project2/yangili1/cdai/genome_index/hs38/gencode.v26.primary_assembly.annotation.genes.bed.gz
