'''
Snakefile

Include modules:
    -   common.smk
    -   noisy.smk
    -   qtl.smk
    -   other.smk

configfiles:
    -   config/config.yaml

NOTE: 
    -   For Geuvadis, currently running on only 1-to-1 samples.
    When running on full Geuvadis dataset, make sure to modify
    accordingly in these rules:
        1.  `Geuvadis_Linked_SampleIDs` in `common.smk`
        2.  `prep_genotype` in `qtl.smk`

'''

__author__ = "Chao Dai"
__email__ = "chaodai@uchicago.edu"


configfile: "config/config.yaml"

wildcard_constraints:
    datasource = "Geuvadis|GTEx",
    population = "YRI|EUR",
    chrom = "chr[0-9]{1,2}",
    window = "[0-9]+"

include: 'rules/common.smk'
include: 'rules/noisy.smk'
include: 'rules/gtex.smk'
include: 'rules/qtl.smk'
include: "rules/other.smk"


