# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

#include: "rules/common.smk"
configfile: "config/config.yaml"


# rule all:
    # input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


# include: "rules/other.smk"
include: 'rules/noisy.smk'
include: 'rules/qtl.smk'

# rule getconda:
#     input: "workflow/envs/leafcutter.yaml"
#     output: touch("getconda.done")
#     conda:
#         "envs/leafcutter.yaml"
#     shell:
#         "echo done"
